//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PhieuCanEntity.proto
namespace TramCanCoDinh
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PhieuCanEntity")]
  public partial class PhieuCanEntity : global::ProtoBuf.IExtensible
  {
    public PhieuCanEntity() {}
    
    private string _MaPhieuCan;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MaPhieuCan", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string MaPhieuCan
    {
      get { return _MaPhieuCan; }
      set { _MaPhieuCan = value; }
    }
    private string _MaTramCan;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"MaTramCan", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string MaTramCan
    {
      get { return _MaTramCan; }
      set { _MaTramCan = value; }
    }
    private string _BienSoXe;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"BienSoXe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string BienSoXe
    {
      get { return _BienSoXe; }
      set { _BienSoXe = value; }
    }
    private readonly global::System.Collections.Generic.List<TramCanCoDinh.PhieuCanEntity.AnhPhieuCan> _ImagesList = new global::System.Collections.Generic.List<TramCanCoDinh.PhieuCanEntity.AnhPhieuCan>();
    [global::ProtoBuf.ProtoMember(4, Name=@"ImagesList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TramCanCoDinh.PhieuCanEntity.AnhPhieuCan> ImagesList
    {
      get { return _ImagesList; }
    }
  
    private double _TocDoXe = default(double);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"TocDoXe", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double TocDoXe
    {
      get { return _TocDoXe; }
      set { _TocDoXe = value; }
    }
    private string _ThoiGianXeVaoTram = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"ThoiGianXeVaoTram", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ThoiGianXeVaoTram
    {
      get { return _ThoiGianXeVaoTram; }
      set { _ThoiGianXeVaoTram = value; }
    }
    private string _NgayCan;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"NgayCan", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string NgayCan
    {
      get { return _NgayCan; }
      set { _NgayCan = value; }
    }
    private int _HinhThucCan = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"HinhThucCan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int HinhThucCan
    {
      get { return _HinhThucCan; }
      set { _HinhThucCan = value; }
    }
    private double _KhoiLuongXeThucTe;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"KhoiLuongXeThucTe", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double KhoiLuongXeThucTe
    {
      get { return _KhoiLuongXeThucTe; }
      set { _KhoiLuongXeThucTe = value; }
    }
    private double _KhoiLuongXeSaiSo;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"KhoiLuongXeSaiSo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double KhoiLuongXeSaiSo
    {
      get { return _KhoiLuongXeSaiSo; }
      set { _KhoiLuongXeSaiSo = value; }
    }
    private double _KhoiLuongXeChoPhep;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"KhoiLuongXeChoPhep", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double KhoiLuongXeChoPhep
    {
      get { return _KhoiLuongXeChoPhep; }
      set { _KhoiLuongXeChoPhep = value; }
    }
    private readonly global::System.Collections.Generic.List<TramCanCoDinh.PhieuCanEntity.BoTruc> _BoTrucs = new global::System.Collections.Generic.List<TramCanCoDinh.PhieuCanEntity.BoTruc>();
    [global::ProtoBuf.ProtoMember(12, Name=@"BoTrucs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TramCanCoDinh.PhieuCanEntity.BoTruc> BoTrucs
    {
      get { return _BoTrucs; }
    }
  
    private string _LanCan = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"LanCan", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string LanCan
    {
      get { return _LanCan; }
      set { _LanCan = value; }
    }
    private string _LanCanXe = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"LanCanXe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string LanCanXe
    {
      get { return _LanCanXe; }
      set { _LanCanXe = value; }
    }
    private string _BienSoRM = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"BienSoRM", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string BienSoRM
    {
      get { return _BienSoRM; }
      set { _BienSoRM = value; }
    }
    private int _LaXeXiTec = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"LaXeXiTec", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int LaXeXiTec
    {
      get { return _LaXeXiTec; }
      set { _LaXeXiTec = value; }
    }
    private string _HoTenLaiXe = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"HoTenLaiXe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string HoTenLaiXe
    {
      get { return _HoTenLaiXe; }
      set { _HoTenLaiXe = value; }
    }
    private string _SoGPLHX = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"SoGPLHX", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SoGPLHX
    {
      get { return _SoGPLHX; }
      set { _SoGPLHX = value; }
    }
    private string _GhiChu = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"GhiChu", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string GhiChu
    {
      get { return _GhiChu; }
      set { _GhiChu = value; }
    }
    private string _NguoiLapPhieu = "";
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"NguoiLapPhieu", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string NguoiLapPhieu
    {
      get { return _NguoiLapPhieu; }
      set { _NguoiLapPhieu = value; }
    }
    private string _MauXe = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"MauXe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string MauXe
    {
      get { return _MauXe; }
      set { _MauXe = value; }
    }
    private string _GPLX = "";
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"GPLX", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string GPLX
    {
      get { return _GPLX; }
      set { _GPLX = value; }
    }
    private int _KichThuocBaoVuotD = default(int);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"KichThuocBaoVuotD", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int KichThuocBaoVuotD
    {
      get { return _KichThuocBaoVuotD; }
      set { _KichThuocBaoVuotD = value; }
    }
    private int _KichThuocBaoVuotR = default(int);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"KichThuocBaoVuotR", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int KichThuocBaoVuotR
    {
      get { return _KichThuocBaoVuotR; }
      set { _KichThuocBaoVuotR = value; }
    }
    private int _KichThuocBaoVuotC = default(int);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"KichThuocBaoVuotC", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int KichThuocBaoVuotC
    {
      get { return _KichThuocBaoVuotC; }
      set { _KichThuocBaoVuotC = value; }
    }
    private int _KichThuocThungVuotD = default(int);
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"KichThuocThungVuotD", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int KichThuocThungVuotD
    {
      get { return _KichThuocThungVuotD; }
      set { _KichThuocThungVuotD = value; }
    }
    private int _KichThuocThungVuotR = default(int);
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"KichThuocThungVuotR", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int KichThuocThungVuotR
    {
      get { return _KichThuocThungVuotR; }
      set { _KichThuocThungVuotR = value; }
    }
    private int _KichThuocThungVuotC = default(int);
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"KichThuocThungVuotC", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int KichThuocThungVuotC
    {
      get { return _KichThuocThungVuotC; }
      set { _KichThuocThungVuotC = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AnhPhieuCan")]
  public partial class AnhPhieuCan : global::ProtoBuf.IExtensible
  {
    public AnhPhieuCan() {}
    
    private string _Anh = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Anh", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Anh
    {
      get { return _Anh; }
      set { _Anh = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BoTruc")]
  public partial class BoTruc : global::ProtoBuf.IExtensible
  {
    public BoTruc() {}
    
    private int _LoaiBoTruc;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"LoaiBoTruc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int LoaiBoTruc
    {
      get { return _LoaiBoTruc; }
      set { _LoaiBoTruc = value; }
    }
    private string _KhoangCachTruc = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"KhoangCachTruc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string KhoangCachTruc
    {
      get { return _KhoangCachTruc; }
      set { _KhoangCachTruc = value; }
    }
    private double _KhoiLuongTrucThucTe;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"KhoiLuongTrucThucTe", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double KhoiLuongTrucThucTe
    {
      get { return _KhoiLuongTrucThucTe; }
      set { _KhoiLuongTrucThucTe = value; }
    }
    private double _KhoiLuongSaiSo;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"KhoiLuongSaiSo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double KhoiLuongSaiSo
    {
      get { return _KhoiLuongSaiSo; }
      set { _KhoiLuongSaiSo = value; }
    }
    private double _KhoiLuongChoPhep;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"KhoiLuongChoPhep", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double KhoiLuongChoPhep
    {
      get { return _KhoiLuongChoPhep; }
      set { _KhoiLuongChoPhep = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}